# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Resources/CalibracaoP.ui'
#
# Created: Fri Nov 10 15:32:01 2017
#      by: PyQt5 UI code generator 5.2.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1366, 695)
        MainWindow.setMinimumSize(QtCore.QSize(817, 0))
        MainWindow.setStyleSheet("background-color:rgb(86, 86, 86);\n"
"color: rgb(255,255,255);")
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setAutoFillBackground(False)
        self.centralWidget.setObjectName("centralWidget")
        self.CentralGraph = QtWidgets.QGraphicsView(self.centralWidget)
        self.CentralGraph.setGeometry(QtCore.QRect(420, 10, 931, 621))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CentralGraph.sizePolicy().hasHeightForWidth())
        self.CentralGraph.setSizePolicy(sizePolicy)
        self.CentralGraph.setObjectName("CentralGraph")
        self.escalaBox = QtWidgets.QGroupBox(self.centralWidget)
        self.escalaBox.setGeometry(QtCore.QRect(20, 10, 391, 231))
        self.escalaBox.setToolTip("")
        self.escalaBox.setStatusTip("")
        self.escalaBox.setWhatsThis("")
        self.escalaBox.setAutoFillBackground(False)
        self.escalaBox.setStyleSheet("background-color: rgb(86, 86, 86);\n"
"border:1px solid rgb(194, 8, 6);\n"
"color: rgb(255, 255, 255);")
        self.escalaBox.setFlat(False)
        self.escalaBox.setCheckable(False)
        self.escalaBox.setObjectName("escalaBox")
        self.forcaBox = QtWidgets.QGroupBox(self.escalaBox)
        self.forcaBox.setGeometry(QtCore.QRect(10, 30, 181, 101))
        self.forcaBox.setObjectName("forcaBox")
        self.f_max = QtWidgets.QLineEdit(self.forcaBox)
        self.f_max.setGeometry(QtCore.QRect(80, 30, 61, 21))
        self.f_max.setObjectName("f_max")
        self.f_max_label = QtWidgets.QLabel(self.forcaBox)
        self.f_max_label.setGeometry(QtCore.QRect(20, 30, 57, 21))
        self.f_max_label.setStyleSheet("border: rgb(255,255,255)")
        self.f_max_label.setObjectName("f_max_label")
        self.f_min_label = QtWidgets.QLabel(self.forcaBox)
        self.f_min_label.setGeometry(QtCore.QRect(20, 60, 57, 21))
        self.f_min_label.setStyleSheet("border:rgb(255,255,255)")
        self.f_min_label.setObjectName("f_min_label")
        self.f_min = QtWidgets.QLineEdit(self.forcaBox)
        self.f_min.setGeometry(QtCore.QRect(80, 60, 61, 21))
        self.f_min.setObjectName("f_min")
        self.pressaoBox = QtWidgets.QGroupBox(self.escalaBox)
        self.pressaoBox.setGeometry(QtCore.QRect(200, 30, 181, 101))
        self.pressaoBox.setObjectName("pressaoBox")
        self.p_max = QtWidgets.QLineEdit(self.pressaoBox)
        self.p_max.setGeometry(QtCore.QRect(80, 30, 61, 21))
        self.p_max.setObjectName("p_max")
        self.p_max_label = QtWidgets.QLabel(self.pressaoBox)
        self.p_max_label.setGeometry(QtCore.QRect(20, 30, 57, 21))
        self.p_max_label.setStyleSheet("border: rgb(255,255,255)")
        self.p_max_label.setObjectName("p_max_label")
        self.p_min_label = QtWidgets.QLabel(self.pressaoBox)
        self.p_min_label.setGeometry(QtCore.QRect(20, 60, 57, 21))
        self.p_min_label.setStyleSheet("border: rgb(255,255,255)")
        self.p_min_label.setObjectName("p_min_label")
        self.p_min = QtWidgets.QLineEdit(self.pressaoBox)
        self.p_min.setGeometry(QtCore.QRect(80, 60, 61, 21))
        self.p_min.setObjectName("p_min")
        self.forcaBox_2 = QtWidgets.QGroupBox(self.escalaBox)
        self.forcaBox_2.setGeometry(QtCore.QRect(100, 140, 171, 81))
        self.forcaBox_2.setObjectName("forcaBox_2")
        self.f_max_2 = QtWidgets.QLineEdit(self.forcaBox_2)
        self.f_max_2.setGeometry(QtCore.QRect(100, 30, 61, 21))
        self.f_max_2.setObjectName("f_max_2")
        self.f_max_label_2 = QtWidgets.QLabel(self.forcaBox_2)
        self.f_max_label_2.setGeometry(QtCore.QRect(10, 30, 81, 21))
        self.f_max_label_2.setStyleSheet("border: rgb(255,255,255)")
        self.f_max_label_2.setObjectName("f_max_label_2")
        self.amostragemBox = QtWidgets.QGroupBox(self.centralWidget)
        self.amostragemBox.setGeometry(QtCore.QRect(20, 250, 181, 71))
        self.amostragemBox.setStyleSheet("border:1px solid rgb(255, 83, 0);\n"
"color: rgb(255,255,255);")
        self.amostragemBox.setObjectName("amostragemBox")
        self.amostragemCBox = QtWidgets.QComboBox(self.amostragemBox)
        self.amostragemCBox.setGeometry(QtCore.QRect(50, 30, 101, 27))
        self.amostragemCBox.setStyleSheet("border-color: rgb(255,255,255);\n"
"background-color: rgb(169, 169, 169);\n"
"")
        self.amostragemCBox.setObjectName("amostragemCBox")
        self.amostragemCBox.addItem("")
        self.amostragemCBox.addItem("")
        self.amostragemCBox.addItem("")
        self.amostragemCBox.addItem("")
        self.amostragemCBox.addItem("")
        self.amostragemCBox.addItem("")
        self.amostragemCBox.addItem("")
        self.amostragemCBox.addItem("")
        self.amostragemCBox.addItem("")
        self.cronometroBox = QtWidgets.QGroupBox(self.centralWidget)
        self.cronometroBox.setGeometry(QtCore.QRect(20, 330, 381, 171))
        self.cronometroBox.setStyleSheet("border:1px solid rgb(123, 0, 129);")
        self.cronometroBox.setObjectName("cronometroBox")
        self.timerOptionButton = QtWidgets.QPushButton(self.cronometroBox)
        self.timerOptionButton.setGeometry(QtCore.QRect(140, 130, 61, 31))
        self.timerOptionButton.setObjectName("timerOptionButton")
        self.initTimerButton = QtWidgets.QPushButton(self.cronometroBox)
        self.initTimerButton.setGeometry(QtCore.QRect(140, 30, 61, 31))
        self.initTimerButton.setObjectName("initTimerButton")
        self.cronometroGBox = QtWidgets.QGroupBox(self.cronometroBox)
        self.cronometroGBox.setGeometry(QtCore.QRect(10, 30, 120, 131))
        self.cronometroGBox.setObjectName("cronometroGBox")
        self.cronometroLabel = QtWidgets.QLabel(self.cronometroGBox)
        self.cronometroLabel.setGeometry(QtCore.QRect(20, 60, 81, 31))
        self.cronometroLabel.setObjectName("cronometroLabel")
        self.horaInicGBox = QtWidgets.QGroupBox(self.cronometroBox)
        self.horaInicGBox.setGeometry(QtCore.QRect(220, 10, 151, 71))
        self.horaInicGBox.setObjectName("horaInicGBox")
        self.horaInicLabel = QtWidgets.QLabel(self.horaInicGBox)
        self.horaInicLabel.setGeometry(QtCore.QRect(30, 30, 91, 31))
        self.horaInicLabel.setStyleSheet("font: 14pt \"Noto Serif\";")
        self.horaInicLabel.setObjectName("horaInicLabel")
        self.horaAtualGBox = QtWidgets.QGroupBox(self.cronometroBox)
        self.horaAtualGBox.setGeometry(QtCore.QRect(220, 90, 151, 71))
        self.horaAtualGBox.setObjectName("horaAtualGBox")
        self.horaAtualLabel = QtWidgets.QLabel(self.horaAtualGBox)
        self.horaAtualLabel.setGeometry(QtCore.QRect(30, 30, 91, 31))
        self.horaAtualLabel.setStyleSheet("font: 14pt \"Noto Serif\";")
        self.horaAtualLabel.setObjectName("horaAtualLabel")
        self.stopTimerButton = QtWidgets.QPushButton(self.cronometroBox)
        self.stopTimerButton.setGeometry(QtCore.QRect(140, 80, 61, 31))
        self.stopTimerButton.setObjectName("stopTimerButton")
        self.prensaNameGBox = QtWidgets.QGroupBox(self.centralWidget)
        self.prensaNameGBox.setGeometry(QtCore.QRect(210, 250, 191, 71))
        self.prensaNameGBox.setStyleSheet("border: 1px solid rgb(27, 144, 0);")
        self.prensaNameGBox.setObjectName("prensaNameGBox")
        self.prensaName = QtWidgets.QLineEdit(self.prensaNameGBox)
        self.prensaName.setGeometry(QtCore.QRect(50, 20, 111, 31))
        self.prensaName.setStyleSheet("font: 12pt \"Noto Serif\";")
        self.prensaName.setObjectName("prensaName")
        self.valAbsolGBox = QtWidgets.QGroupBox(self.centralWidget)
        self.valAbsolGBox.setGeometry(QtCore.QRect(20, 510, 381, 111))
        self.valAbsolGBox.setStyleSheet("border: 1px solid rgb(26, 149, 172)")
        self.valAbsolGBox.setObjectName("valAbsolGBox")
        self.forcaGBox = QtWidgets.QGroupBox(self.valAbsolGBox)
        self.forcaGBox.setGeometry(QtCore.QRect(20, 30, 161, 71))
        self.forcaGBox.setObjectName("forcaGBox")
        self.forcaLabel = QtWidgets.QLabel(self.forcaGBox)
        self.forcaLabel.setGeometry(QtCore.QRect(20, 30, 121, 31))
        self.forcaLabel.setStyleSheet("font: 14pt \"Noto Serif\";")
        self.forcaLabel.setObjectName("forcaLabel")
        self.calibranteGBox = QtWidgets.QGroupBox(self.valAbsolGBox)
        self.calibranteGBox.setGeometry(QtCore.QRect(200, 30, 161, 71))
        self.calibranteGBox.setObjectName("calibranteGBox")
        self.calibranteLabel = QtWidgets.QLabel(self.calibranteGBox)
        self.calibranteLabel.setGeometry(QtCore.QRect(20, 30, 131, 31))
        self.calibranteLabel.setStyleSheet("font: 14pt \"Noto Serif\";")
        self.calibranteLabel.setObjectName("calibranteLabel")
        self.arquivoSalvoLabel = QtWidgets.QLabel(self.centralWidget)
        self.arquivoSalvoLabel.setGeometry(QtCore.QRect(20, 630, 111, 16))
        self.arquivoSalvoLabel.setObjectName("arquivoSalvoLabel")
        self.arqSalvoLabel = QtWidgets.QLabel(self.centralWidget)
        self.arqSalvoLabel.setGeometry(QtCore.QRect(140, 630, 241, 16))
        self.arqSalvoLabel.setObjectName("arqSalvoLabel")
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1366, 23))
        self.menuBar.setObjectName("menuBar")
        self.menuArquivo = QtWidgets.QMenu(self.menuBar)
        self.menuArquivo.setObjectName("menuArquivo")
        self.menuEtapa = QtWidgets.QMenu(self.menuBar)
        self.menuEtapa.setObjectName("menuEtapa")
        MainWindow.setMenuBar(self.menuBar)
        self.menuStatusBar = QtWidgets.QStatusBar(MainWindow)
        self.menuStatusBar.setObjectName("menuStatusBar")
        MainWindow.setStatusBar(self.menuStatusBar)
        self.alternaCalibraP = QtWidgets.QAction(MainWindow)
        self.alternaCalibraP.setObjectName("alternaCalibraP")
        self.alternaCalibraT = QtWidgets.QAction(MainWindow)
        self.alternaCalibraT.setObjectName("alternaCalibraT")
        self.alternaProc = QtWidgets.QAction(MainWindow)
        self.alternaProc.setObjectName("alternaProc")
        self.botaoAbrir = QtWidgets.QAction(MainWindow)
        self.botaoAbrir.setIconVisibleInMenu(True)
        self.botaoAbrir.setObjectName("botaoAbrir")
        self.actionSalvar = QtWidgets.QAction(MainWindow)
        self.actionSalvar.setObjectName("actionSalvar")
        self.actionSalvar_Como = QtWidgets.QAction(MainWindow)
        self.actionSalvar_Como.setObjectName("actionSalvar_Como")
        self.botaoSalvar = QtWidgets.QAction(MainWindow)
        self.botaoSalvar.setObjectName("botaoSalvar")
        self.botaoSalvarComo = QtWidgets.QAction(MainWindow)
        self.botaoSalvarComo.setObjectName("botaoSalvarComo")
        self.menuArquivo.addAction(self.botaoAbrir)
        self.menuArquivo.addAction(self.botaoSalvar)
        self.menuArquivo.addAction(self.botaoSalvarComo)
        self.menuEtapa.addAction(self.alternaCalibraP)
        self.menuEtapa.addAction(self.alternaCalibraT)
        self.menuEtapa.addAction(self.alternaProc)
        self.menuBar.addAction(self.menuArquivo.menuAction())
        self.menuBar.addAction(self.menuEtapa.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SADAMAP - Análise de Dados: Etapa 1 - Calibração de Pressão"))
        self.escalaBox.setTitle(_translate("MainWindow", "Escalas de Visualização (Range)"))
        self.forcaBox.setTitle(_translate("MainWindow", "Força"))
        self.f_max.setText(_translate("MainWindow", "100"))
        self.f_max_label.setText(_translate("MainWindow", "Máximo:"))
        self.f_min_label.setText(_translate("MainWindow", "Mínimo:"))
        self.pressaoBox.setTitle(_translate("MainWindow", "Tensão no Calibrante"))
        self.p_max_label.setText(_translate("MainWindow", "Máximo:"))
        self.p_min_label.setText(_translate("MainWindow", "Mínimo:"))
        self.forcaBox_2.setTitle(_translate("MainWindow", "Tempo"))
        self.f_max_label_2.setText(_translate("MainWindow", "Intervalo (s):"))
        self.amostragemBox.setTitle(_translate("MainWindow", "Amostragem"))
        self.amostragemCBox.setItemText(0, _translate("MainWindow", "100 mseg"))
        self.amostragemCBox.setItemText(1, _translate("MainWindow", "200 mseg"))
        self.amostragemCBox.setItemText(2, _translate("MainWindow", "500 mseg"))
        self.amostragemCBox.setItemText(3, _translate("MainWindow", "1 seg"))
        self.amostragemCBox.setItemText(4, _translate("MainWindow", "1.5 seg"))
        self.amostragemCBox.setItemText(5, _translate("MainWindow", "2 seg"))
        self.amostragemCBox.setItemText(6, _translate("MainWindow", "2.5 seg"))
        self.amostragemCBox.setItemText(7, _translate("MainWindow", "5 seg"))
        self.amostragemCBox.setItemText(8, _translate("MainWindow", "10 seg"))
        self.cronometroBox.setTitle(_translate("MainWindow", "Timer"))
        self.timerOptionButton.setText(_translate("MainWindow", "Opções"))
        self.initTimerButton.setText(_translate("MainWindow", "Iniciar"))
        self.cronometroGBox.setTitle(_translate("MainWindow", "Cronômetro"))
        self.cronometroLabel.setText(_translate("MainWindow", "10.2674 s"))
        self.horaInicGBox.setTitle(_translate("MainWindow", "Horário de Início"))
        self.horaInicLabel.setText(_translate("MainWindow", "16:30:15"))
        self.horaAtualGBox.setTitle(_translate("MainWindow", "Horário Atual"))
        self.horaAtualLabel.setText(_translate("MainWindow", "17:05:56"))
        self.stopTimerButton.setText(_translate("MainWindow", "Parar"))
        self.prensaNameGBox.setTitle(_translate("MainWindow", "Prensa"))
        self.prensaName.setText(_translate("MainWindow", "Pr 400 Tonf"))
        self.valAbsolGBox.setTitle(_translate("MainWindow", "Valores Absolutos"))
        self.forcaGBox.setTitle(_translate("MainWindow", "Força"))
        self.forcaLabel.setText(_translate("MainWindow", "-42.679 Tonf"))
        self.calibranteGBox.setTitle(_translate("MainWindow", "Tensão no Calibrante"))
        self.calibranteLabel.setText(_translate("MainWindow", "-23.804 mV"))
        self.arquivoSalvoLabel.setText(_translate("MainWindow", "Arquivo Salvo em:"))
        self.arqSalvoLabel.setText(_translate("MainWindow", "/home/LAPMA/Pressao/1025565.pre"))
        self.menuArquivo.setTitle(_translate("MainWindow", "Arquivo"))
        self.menuEtapa.setTitle(_translate("MainWindow", "Etapa"))
        self.alternaCalibraP.setText(_translate("MainWindow", "Calibração P"))
        self.alternaCalibraT.setText(_translate("MainWindow", "Calibração T"))
        self.alternaProc.setText(_translate("MainWindow", "Processamento"))
        self.botaoAbrir.setText(_translate("MainWindow", "Abrir"))
        self.actionSalvar.setText(_translate("MainWindow", "Salvar"))
        self.actionSalvar_Como.setText(_translate("MainWindow", "Salvar Como"))
        self.botaoSalvar.setText(_translate("MainWindow", "Salvar"))
        self.botaoSalvarComo.setText(_translate("MainWindow", "Salvar Como"))

    def sceneSelector(self, scene):
        self.CentralGraph.setScene(scene)
        self.CentralGraph.setBackgroundBrush(QtCore.Qt.black)